# Generated by Django 5.0.6 on 2024-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
    ]
