# Generated by Django 5.0.6 on 2024-07-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
