# Generated by Django 5.0.6 on 2024-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_userinfo_is_active_userinfo_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
