# Generated by Django 5.0.6 on 2024-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userinfo', '0004_userinfo_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'permissions': []},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='userinfo_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='userinfo_set', to='auth.permission'),
        ),
    ]
