# Generated by Django 5.0.6 on 2024-07-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_alter_userinfo_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
    ]
